title: Trip Shift
author: CRYMore Studios
email: your-email@domain.com
description: Welcome to Trip Shift, the industrial horror game that takes you on a mind-bending journey through an otherworldly clothes factory.  Navigate through a series of strange and twisted tasks given to you by an unseen supervisor, all while battling the effects of powerful drugs that alter your perception and gameplay mechanics. Can you make it through the six surreal days and escape the factory before it's too late?
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: samarsault/texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Trip Shift
  tagline: Surrealist Horror Game
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  Viibrant
    linkedIn: in/connorbrook
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
